### ISSUE TITLE
Grant access to "housewares" AWS s3 database for team members.

### ISSUE THREAD

**Issue by jkeane889** [ForgEtsy/forgEtsy_Reviews#6]
Look into granting access to AWS S3 server for all team members looking to incorporate "housewares" pictures into their components.

**Comment by projectLewis** [comment]
Everyone should have access to the images. Thats why we set them to public on aws when we uploaded them. No special privileges should be required.

**Comment by jkeane889** [comment]
Unnecessary to do.
